hankookin123/Seoul

seoul-react/src/App.js
=> 강좌 탭 수정 --> 환경

seoul-react/src/App.js, seoul-react/src/assets/css/health/HealthMain.module.css, seoul-react/src/components/health/HealthMain.js, seoul-spring/src/main/java/com/tech/seoul/environment/controllers/EnvironmentController.java, seoul-spring/src/main/java/com/tech/seoul/environment/models/EnvironmentDao.java, seoul-spring/src/main/java/com/tech/seoul/environment/service/EnvironmentService.java, seoul-spring/src/main/java/com/tech/seoul/health/controllers/HealthController.java, seoul-spring/src/main/java/com/tech/seoul/health/models/HealthDao.java, seoul-spring/src/main/java/com/tech/seoul/health/service/HealthService.java, seoul-spring/src/main/resources/mybatis/mapper/culture/HealthDao.xml
=> health 폴더/파일 생성 및 테스트

seoul-react/src/assets/css/common/Common.module.css, seoul-react/src/assets/css/common/SideTab.module.css, seoul-react/src/assets/css/culture/CultureMain.module.css, seoul-react/src/components/common/CommonMap.js, seoul-react/src/components/common/SideTab.js, seoul-react/src/components/culture/CultureMain.js
=> 공통 지도 작업 완

seoul-react/src/App.js, seoul-react/src/components/culture/CultureMain.js, seoul-react/src/components/db/InsertDB.js, seoul-react/src/components/health/HealthMain.js, seoul-react/src/db/sendFetchPost.js, seoul-react/src/hooks/getFetch.js, seoul-spring/build.gradle, seoul-spring/src/main/java/com/tech/seoul/culture/controllers/CultureController.java, seoul-spring/src/main/java/com/tech/seoul/culture/models/CultureBookDto.java, seoul-spring/src/main/java/com/tech/seoul/culture/models/CultureDao.java, seoul-spring/src/main/java/com/tech/seoul/culture/service/CultureService.java, seoul-spring/src/main/resources/mybatis/mapper/culture/CultureDao.xml
=> 디비 인서트 기능 추가, 디비 정보 획득 기능 추가

seoul-react/src/components/db/InsertDB.js, seoul-react/src/components/health/HealthMain.js, seoul-spring/src/main/java/com/tech/seoul/health/controllers/HealthController.java, seoul-spring/src/main/java/com/tech/seoul/health/models/HealthDao.java, seoul-spring/src/main/java/com/tech/seoul/health/service/HealthService.java, seoul-spring/src/main/resources/mybatis/mapper/health/HealthDao.xml
=> 건강 페이지 오류 수정

seoul-react/src/assets/css/culture/CultureMain.module.css, seoul-react/src/components/culture/CultureBooKStore.js, seoul-react/src/components/culture/CultureMain.js
=> 서점 디테일 뷰 추가

seoul-react/src/assets/css/health/HealthMain.module.css, seoul-react/src/components/health/HealthMain.js, seoul-spring/src/main/java/com/tech/seoul/health/controllers/HealthController.java, seoul-spring/src/main/java/com/tech/seoul/health/models/HealthDao.java, seoul-spring/src/main/java/com/tech/seoul/health/service/HealthService.java, seoul-spring/src/main/resources/mybatis/mapper/health/HealthDao.xml
=> 건강 페이지 검색 및 지도 마커 표시

seoul-react/src/assets/css/health/HealthMain.module.css, seoul-react/src/components/health/HealthMain.js, seoul-spring/src/main/java/com/tech/seoul/health/controllers/HealthController.java, seoul-spring/src/main/java/com/tech/seoul/health/models/HealthDao.java, seoul-spring/src/main/java/com/tech/seoul/health/models/HospitalDto.java, seoul-spring/src/main/java/com/tech/seoul/health/service/HealthService.java, seoul-spring/src/main/resources/mybatis/mapper/health/HealthDao.xml
=> 병원 리스트 간단정보 수정

seoul-react/src/assets/css/health/HealthMain.module.css, seoul-react/src/components/health/HealthMain.js, seoul-spring/src/main/java/com/tech/seoul/health/controllers/HealthController.java, seoul-spring/src/main/java/com/tech/seoul/health/models/HealthDao.java, seoul-spring/src/main/java/com/tech/seoul/health/service/HealthService.java, seoul-spring/src/main/resources/mybatis/mapper/health/HealthDao.xml
=> 진료과목 필터 구현

seoul-react/src/assets/css/health/HealthMain.module.css, seoul-react/src/components/health/HealthMain.js, seoul-spring/src/main/java/com/tech/seoul/health/controllers/HealthController.java, seoul-spring/src/main/java/com/tech/seoul/health/models/HealthDao.java, seoul-spring/src/main/java/com/tech/seoul/health/service/HealthService.java, seoul-spring/src/main/resources/mybatis/mapper/health/HealthDao.xml
=> 주말/공휴일 필터 구현

seoul-react/src/components/tour/MapComponent.css, seoul-react/src/components/tour/MapComponent.jsx, seoul-react/src/components/tour/MapComponentFestival.css, seoul-react/src/components/tour/MapComponentFestival.jsx, seoul-spring/src/main/java/com/tech/seoul/tour/tourFestival/TourFestivalDTO.java, seoul-spring/src/main/java/com/tech/seoul/tour/tourFestival/TourFestivalRepository.java, seoul-spring/src/main/java/com/tech/seoul/tour/tourFestival/TourFestivalService.java, seoul-spring/src/main/java/com/tech/seoul/tour/tourInfo/TourInfoDTO.java, seoul-spring/src/main/java/com/tech/seoul/tour/tourInfo/TourInfoRepository.java, seoul-spring/src/main/java/com/tech/seoul/tour/tourInfo/TourInfoService.java
css 수정
console.log delete
축제 상세정보 추가
관광 상세정보 나누기
=> 문의처, 이용시간 추가

seoul-react/src/components/health/HealthMain.js, seoul-spring/src/main/java/com/tech/seoul/health/controllers/HealthController.java, seoul-spring/src/main/java/com/tech/seoul/health/models/HealthDao.java, seoul-spring/src/main/java/com/tech/seoul/health/service/HealthService.java, seoul-spring/src/main/resources/mybatis/mapper/health/HealthDao.xml
현재위치 마커 오버레이 설정 및 필터 적용한 키워드 검색 수정
=> 현재위치 마커 오버레이 설정 및 필터 적용한 키워드 검색 수정

seoul-react/src/components/health/HealthMain.js, seoul-spring/src/main/resources/mybatis/mapper/health/HealthDao.xml
=> 동일한 위치에 있는 병원 마커 위에 병원 개수 표시

seoul-react/src/assets/css/culture/CultureMain.module.css, seoul-react/src/components/culture/CultureAssetsInfo.js, seoul-react/src/components/culture/CultureAssetsMain.js, seoul-react/src/components/culture/CultureAssetsSearch.js, seoul-react/src/components/culture/CultureMain.js, seoul-react/src/components/culture/CultureMuseumSearch.js, seoul-spring/src/main/java/com/tech/seoul/culture/controllers/CultureController.java
=> 문화 문화재 파트 완

seoul-react/src/assets/css/health/HealthMain.module.css, seoul-react/src/components/health/HealthMain.js, seoul-react/src/components/health/HospitalDetail.js
=> 병원 상세정보 컴포넌트 분리 및 부분 수정

seoul-react/src/components/health/HealthMain.js
=> 지도 클릭 시 마커 선택된 마커 해제

seoul-react/src/App.js, seoul-react/src/assets/css/main/Home.module.css, seoul-react/src/components/main/Home.js
=> 메인화면 오른쪽 상단에 날씨정보 컴포넌트 추가

seoul-react/src/App.js, seoul-react/src/assets/css/main/Home.module.css, seoul-react/src/components/culture/CultureMain.js, seoul-react/src/components/culture/CultureMovieInfo.js, seoul-react/src/components/culture/CultureMovieSearch.js, seoul-react/src/components/culture/CulturePerformSearch.js, seoul-react/src/components/culture/CultureSpaceInfo.js, seoul-react/src/components/culture/CultureSpaceMain.js, seoul-spring/src/main/java/com/tech/seoul/culture/controllers/CultureController.java, seoul-spring/src/main/java/com/tech/seoul/culture/models/CultureDao.java, seoul-spring/src/main/java/com/tech/seoul/culture/models/CultureMovieInfoDto.java, seoul-spring/src/main/java/com/tech/seoul/culture/service/CultureService.java, seoul-spring/src/main/resources/application.properties, seoul-spring/src/main/resources/mybatis/mapper/culture/CultureDao.xml
=> 문화 공연 파트 완

seoul-react/src/components/health/HealthMain.js, seoul-react/src/components/health/WeatherInfo.jsx
API 제공 시간(매시 45분)에 따라 조건 수정
0시일 경우 23으로 설정(newHour), 0이 아닌 경우는 추출한 시각에서 마이너스 1
hour 또는 newHour가 10보다 작을 경우, 앞에 0 추가
=> 실시간 날씨 데이터 오류 수정

seoul-react/src/App.js, seoul-react/src/assets/css/main/Home.module.css, seoul-react/src/components/culture/CultureMain.js, seoul-react/src/components/culture/assets/CulturalAssetsTabSection.js, seoul-react/src/components/culture/assets/CultureAssetsInfo.js, seoul-react/src/components/culture/assets/CultureAssetsMain.js, seoul-react/src/components/culture/assets/CultureAssetsSearch.js, seoul-react/src/components/culture/book/BookTabSection.js, seoul-react/src/components/culture/book/CultureBooKStore.js, seoul-react/src/components/culture/book/CultureBookLibrary.js, seoul-react/src/components/culture/book/CultureBookMain.js, seoul-react/src/components/culture/book/CultureBookSearch.js, seoul-react/src/components/culture/museum/CultureArtMuseumInfo.js, seoul-react/src/components/culture/museum/CultureMuseumInfo.js, seoul-react/src/components/culture/museum/CultureMuseumMain.js, seoul-react/src/components/culture/museum/CultureMuseumSearch.js, seoul-react/src/components/culture/museum/MuseumTabSection.js, seoul-react/src/components/culture/performance/CultureMovieInfo.js, seoul-react/src/components/culture/performance/CultureMovieSearch.js, seoul-react/src/components/culture/performance/CulturePerformSearch.js, seoul-react/src/components/culture/performance/CultureSpaceInfo.js, seoul-react/src/components/culture/performance/CultureSpaceMain.js, seoul-react/src/components/culture/performance/PerformanceTabSection.js, seoul-react/src/components/health/WeatherInfo.jsx, seoul-react/src/components/main/Home.js
=> 문화 파트 덱압축중

seoul-react/src/assets/css/health/HealthMain.module.css, seoul-react/src/components/health/HealthMain.js, seoul-react/src/components/health/HospitalDetail.js, seoul-react/src/components/health/WeatherInfo.jsx, seoul-spring/src/main/java/com/tech/seoul/ApiExplorerHealthHospitalInfo.java, seoul-spring/src/main/java/com/tech/seoul/ApiExplorerHealthPharmacy.java, seoul-spring/src/main/java/com/tech/seoul/health/controllers/HealthController.java, seoul-spring/src/main/java/com/tech/seoul/health/models/HealthDao.java, seoul-spring/src/main/java/com/tech/seoul/health/models/PharmacyDto.java, seoul-spring/src/main/java/com/tech/seoul/health/service/HealthService.java, seoul-spring/src/main/resources/mybatis/mapper/health/HealthDao.xml
병원 근처 약국 목록
병원 상세정보 아래 부분에 병원 근처 약국 맥시멈 3개 보여주기
=> 병원 근처 약국 목록 중간 수정

seoul-react/src/assets/css/culture/CultureMain.module.css, seoul-react/src/components/culture/CultureMain.js, seoul-react/src/components/culture/assets/CulturalAssetsTabSection.js, seoul-react/src/components/culture/assets/CultureAssetsMain.js, seoul-react/src/components/culture/assets/CultureAssetsSearch.js, seoul-react/src/components/culture/book/BookTabSection.js, seoul-react/src/components/culture/book/CultureBookMain.js, seoul-react/src/components/culture/book/CultureBookSearch.js, seoul-react/src/components/culture/museum/CultureArtMuseumInfo.js, seoul-react/src/components/culture/museum/CultureMuseumMain.js, seoul-react/src/components/culture/museum/CultureMuseumSearch.js, seoul-react/src/components/culture/museum/MuseumTabSection.js, seoul-react/src/components/culture/performance/CultureMovieSearch.js, seoul-react/src/components/culture/performance/CulturePerformSearch.js, seoul-react/src/components/culture/performance/CultureSpaceMain.js, seoul-react/src/components/culture/performance/PerformanceTabSection.js
=> 문화 파트 리액트 파트 정리 완

seoul-react/src/components/common/CommonMap.js, seoul-react/src/components/culture/CultureMain.js, seoul-react/src/components/culture/performance/CultureMovieInfo.js, seoul-react/src/components/culture/performance/CultureSpaceInfo.js
=> 사소한 오류들 수정
